# Generated by Django 5.1.3 on 2024-11-13 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=256)),
                ('Telefone', models.CharField(max_length=11)),
                ('CPF', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('NR_conta', models.CharField(max_length=5)),
                ('NR_agencia', models.CharField(max_length=3)),
                ('DT_cadastro', models.DateTimeField(auto_now_add=True)),
                ('tipo_conta', models.CharField(choices=[('Corrente', 'Corrente'), ('Poupanca', 'Poupanca')], max_length=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id_movimento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimento', models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito')], max_length=10)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.conta')),
            ],
        ),
    ]
