# Generated by Django 5.1.3 on 2024-11-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
