# Generated by Django 5.1.3 on 2024-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_cliente_is_staff_alter_cliente_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
