# Generated by Django 5.1.3 on 2024-11-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_conta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
