# Generated by Django 5.1.3 on 2024-11-26 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_conta_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimento',
            old_name='data',
            new_name='datas',
        ),
        migrations.AddField(
            model_name='movimento',
            name='conta_destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Transferencias_Recebidas', to='banco.conta'),
        ),
        migrations.AddField(
            model_name='movimento',
            name='saldo_movimento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimento',
            name='id_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='banco.conta'),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='tipo_movimento',
            field=models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito'), ('Transferencia', 'Transferência')], max_length=13),
        ),
    ]
