# Generated by Django 5.1.3 on 2024-11-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0007_rename_data_movimento_datas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimento',
            old_name='datas',
            new_name='data',
        ),
    ]
