# Generated by Django 5.1.3 on 2024-11-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0008_alter_cliente_telefone'),
        ('banco', '0008_alter_conta_saldo'),
    ]

    operations = [
    ]
