# Generated by Django 5.1.3 on 2024-11-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0008_rename_datas_movimento_data'),
        ('banco', '0009_merge_20241126_1941'),
    ]

    operations = [
    ]
