# Generated by Django 5.1.3 on 2024-11-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Telefone', models.IntegerField()),
                ('CPF', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=2)),
                ('Pais', models.CharField(max_length=35)),
            ],
        ),
    ]
