# Generated by Django 5.1.3 on 2024-11-12 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contas_Bancarias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta_bancaria',
            old_name='Data_criaçao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='conta_bancaria',
            old_name='Número_conta',
            new_name='numero_conta',
        ),
        migrations.RenameField(
            model_name='conta_bancaria',
            old_name='Saldo',
            new_name='saldo',
        ),
        migrations.RenameField(
            model_name='conta_bancaria',
            old_name='Titular',
            new_name='titular',
        ),
    ]
