# Generated by Django 5.1.3 on 2024-11-13 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas_Bancarias', '0002_rename_data_criaçao_conta_bancaria_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta_Corrente',
            fields=[
                ('conta_bancaria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Contas_Bancarias.conta_bancaria')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            bases=('Contas_Bancarias.conta_bancaria',),
        ),
        migrations.CreateModel(
            name='Conta_Poupanca',
            fields=[
                ('conta_bancaria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Contas_Bancarias.conta_bancaria')),
                ('taxa_juros', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            bases=('Contas_Bancarias.conta_bancaria',),
        ),
    ]
